package com.example.demo.models;

public enum TravelerTypes {
    ADVENTURE_TRAVELER,
    CULTURAL_ENTHUSIAST,
    SOLO_TRAVELER,
    LUXURY_TRAVELER,
    BUDGET_BACKPACKER,
    ECO_TRAVELER,
    FOODIE_TRAVELER,
    BEACH_BUM,
    DIGITAL_NOMAD,
    PILGRIM_TRAVELER,
    WILDLIFE_ENTHUSIAST,
    PHOTOGRAPHER_TRAVELER,
    HISTORY_BUFF,
    FAMILY_VACATIONER,
    FESTIVAL_HOPPER,
    WELLNESS_TRAVELER,
    SPORTS_FANATIC,
    ROAD_TRIPPER,
    CRUISE_TRAVELER,
    URBAN_EXPLORER,
    MISC_TRAVELER;
}
